services:
  - type: web
    name: iwasms-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: daphne -b 0.0.0.0 -p $PORT iwasms.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: iwasms.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
