# Generated by Django 4.2.7 on 2026-06-11 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('ip_block', 'IP Blocked'), ('rate_limit', 'Rate Limited'), ('session_kill', 'Session Terminated'), ('notify', 'Notification Sent'), ('escalate', 'Escalated to Admin'), ('manual', 'Manual Action')], max_length=50)),
                ('description', models.TextField(default='')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_actions', to='alerts.securityalert')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('classify', 'Classify Request'), ('alert_created', 'Alert Created'), ('alert_resolved', 'Alert Resolved'), ('alert_false_positive', 'Alert Marked False Positive'), ('model_retrain', 'Model Retrain Triggered'), ('model_promoted', 'Model Promoted to Active'), ('ip_blocked', 'IP Blocked'), ('export', 'Data Exported'), ('config_change', 'Configuration Changed')], db_index=True, max_length=50)),
                ('resource_type', models.CharField(blank=True, default='', max_length=100)),
                ('resource_id', models.CharField(blank=True, default='', max_length=255)),
                ('detail', models.JSONField(default=dict)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'action'], name='core_auditl_timesta_368b53_idx'), models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx')],
            },
        ),
    ]
