# Generated by Django 4.2.7 on 2026-06-11 20:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(max_length=500)),
                ('organization', models.CharField(max_length=255)),
                ('api_key', models.CharField(blank=True, max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('http_method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('user_agent', models.TextField(blank=True, default='')),
                ('raw_request', models.JSONField(default=dict)),
                ('attack_type', models.CharField(db_index=True, default='normal', max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('normal', 'Normal')], db_index=True, default='normal', max_length=20)),
                ('is_attack', models.BooleanField(db_index=True, default=False)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('processing_latency_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('web_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.webapplication')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'severity'], name='events_secu_timesta_d2e9b0_idx'), models.Index(fields=['source_ip', 'timestamp'], name='events_secu_source__b5ad7e_idx'), models.Index(fields=['attack_type', 'is_attack'], name='events_secu_attack__e35a96_idx')],
            },
        ),
    ]
