# Generated by Django 4.2.7 on 2026-06-11 20:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('model_path', models.CharField(max_length=500)),
                ('scaler_path', models.CharField(blank=True, default='', max_length=500)),
                ('meta_learner_path', models.CharField(blank=True, default='', max_length=500)),
                ('label_map_path', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('accuracy', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('auc_roc', models.FloatField(default=0.0)),
                ('false_positive_rate', models.FloatField(default=0.0)),
                ('trained_on_samples', models.IntegerField(default=0)),
                ('training_duration_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_label', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('raw_probabilities', models.JSONField(default=dict)),
                ('inference_time_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='events.securityevent')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml.mlmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
