# Generated by Django 4.2.7 on 2026-06-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='label_map_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='meta_learner_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='model_path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='scaler_path',
            field=models.TextField(blank=True, default=''),
        ),
    ]
